### ISSUE TITLE
ZBReplay :UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by muralikrishnaj** [riverloopsec/killerbee#137]

**Comment by muralikrishnaj** [comment]
While i'm running zbreplay it throwing error like below:

DEBUG: Received operation timed out error ...attempting to continue.
Traceback (most recent call last):
  File "./zbreplay", line 86, in <module>
    kb.inject(packet[0:-2])
  File "build/bdist.linux-x86_64/egg/killerbee/__init__.py", line 288, in inject
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 424, in inject
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 284, in __usb_write
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by rmspeers** [comment]
Which version of firmware are you running on the rzusbstick? What version of Killerbee are you running?

**Comment by muralikrishnaj** [comment]
@rmspeers Thanks for the quick response. Sort it out by changing the value of injecting packet like
kb.inject(packet[0:-2]) to kb.inject(packet[0:-1])
