### ISSUE TITLE
kbsniff, bug switching channels?

### ISSUE THREAD

**Issue by mstekker** [riverloopsec/killerbee#188]
Hi,

I am trying to sniff al zigbee channels using killerbee.scapy_extensions with the following code:

for chan in zig_chans:
  kbsniff (channel=chan, timeout=zig_timeout, prn=zig_handler, iface=sniffer)
  time.sleep (zig_timeout + 10)

The first iteration works fine, but after the first an exception is thrown:

USBError: [Errno 16] Resource busy 

It seems the USB Resource is still busy after the time out.

Doe anyone has any clues how to switch the chans?

Full exception:

Traceback (most recent call last):
File "/home/dev/killerbee/killerbee/tools/zigsnif.py", line 84, in <module>
kbsniff (channel=chan, timeout=zig_timeout, prn=zig_handler, iface=sniffer)
File "build/bdist.linux-x86_64/egg/killerbee/scapy_extensions.py", line 217, in kbsniff
kb = KillerBee(device = iface)
File "build/bdist.linux-x86_64/egg/killerbee/__init__.py", line 120, in __init__
self.driver = CC253x(self.dev, self.__bus, CC253x.VARIANT_CC2531)
File "build/bdist.linux-x86_64/egg/killerbee/dev_cc253x.py", line 60, in __init__
self.dev.set_configuration()
File "/usr/lib/python2.7/dist-packages/usb/core.py", line 869, in set_configuration
self._ctx.managed_set_configuration(self, configuration)
File "/usr/lib/python2.7/dist-packages/usb/core.py", line 102, in wrapper
return f(self, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/usb/core.py", line 148, in managed_set_configuration
self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 794, in set_configuration
_check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
raise USBError(_strerror(ret), ret, _libusb_errno[ret])
USBError: [Errno 16] Resource busy
>>> 

Thanks in advance,

Mart

**Comment by mstekker** [comment]
solved:
dev = KillerBee(device=kbutils.devlist()[0][0])
kbsniff (channel=chan, timeout=zig_timeout, prn=zig_handler, iface=dev)

did not know that device could be an instance of KillerBee. With KillerBee.set_channel all works fine now.

Regards,

Mart
