### ISSUE TITLE
killerbee doesn't work on RZUSBSTICK

### ISSUE THREAD

**Issue by CHEN8-1** [riverloopsec/killerbee#239]
I have installed killerbee on ubuntu20.04 , but it doesn't work

when i use zbstumbler

root@com:/home/peter/killerbee-develop# zbstumbler -v
Auto-detection is being deprecated - Please specify hardware
Warning: You are using pyUSB 1.x, support is in beta.
zbstumbler: Transmitting and receiving on interface '2:5'
Setting channel to 11.
Transmitting beacon request.
ERROR: Unable to inject packet: can't concat str to bytes

when i use zbdump, it can't sniffer any packects

root@com:/home/peter/killerbee-develop# zbdump -c 11 -w operating.pcap
Autodetection features will be deprecated - please include interface string (e.g. -i /dev/ttyUSB0)
Autodetection features will be deprecated - please include device string (e.g. -d apimote)
Auto-detection is being deprecated - Please specify hardware
Warning: You are using pyUSB 1.x, support is in beta.
zbdump: listening on 'None', channel 11, page 0 (2405.0 MHz), link-type DLT_IEEE802_15_4, capture size 127 bytes

when i use zbwireshark

root@com:/home/peter/killerbee-develop# zbwireshark -c 11
Auto-detection is being deprecated - Please specify hardware
Warning: You are using pyUSB 1.x, support is in beta.
zbwireshark: listening on '2:5', channel 11, page 0 (2405.0 MHz), link-type DLT_IEEE802_15_4, capture size 127 bytes
Traceback (most recent call last):
  File "/usr/local/bin/zbwireshark", line 4, in <module>
    __import__('pkg_resources').run_script('killerbee==3.0.0b2', 'zbwireshark')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/killerbee-3.0.0b2-py3.8-linux-x86_64.egg/EGG-INFO/scripts/zbwireshark", line 108, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/killerbee-3.0.0b2-py3.8-linux-x86_64.egg/EGG-INFO/scripts/zbwireshark", line 84, in main
    packet = kb.pnext()
  File "/usr/local/lib/python3.8/dist-packages/killerbee-3.0.0b2-py3.8-linux-x86_64.egg/killerbee/__init__.py", line 442, in pnext
    return self.driver.pnext(timeout)
  File "/usr/local/lib/python3.8/dist-packages/killerbee-3.0.0b2-py3.8-linux-x86_64.egg/killerbee/dev_rzusbstick.py", line 608, in pnext
    ret[0] = ''.join(framedata[:-1])
TypeError: sequence item 0: expected str instance, bytes found

**Comment by eshanaswar** [comment]
Try using the Release version 2.7.2 with python2. (https://github.com/riverloopsec/killerbee/releases/tag/2.7.2)

This worked for me.

**Comment by martijnthe** [comment]
Fix here: https://github.com/riverloopsec/killerbee/pull/242
