### ISSUE TITLE
Get "usb.USBError: Connection timed out" when executing zbdump

### ISSUE THREAD

**Issue by GoogleCodeExporter** [riverloopsec/killerbee#29]
```
What steps will reproduce the problem?
1. Install prerequisites, install from KB source, plug in RZUSBSTICK
2. Run "sudo zbid", returns "007:002 RZUSBSTICK 00DEADBEEF00"
3.Run "sudo zbdump -c 25 -w test.pcap", returns a USB timeout

What is the expected output? What do you see instead?
Not sure what to expect, it's never ran successfully, but here is what I get:
---
Traceback (most recent call last):
  File "/usr/local/bin/zbdump", line 5, in <module>
    pkg_resources.run_script('killerbee==2.5.0', 'zbdump')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/killerbee-2.5.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/zbdump", line 71, in <module>
    
  File "build/bdist.linux-x86_64/egg/killerbee/__init__.py", line 249, in set_channel
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 383, in set_channel
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 299, in _set_mode
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 263, in __usb_write
usb.USBError: Connection timed out
---

What version of the product are you using?
[ ] KillerBee 1.0 (from TAR file)
[X] KillerBee beta (from SVN checkout) Revision # ? (used the latest version as 
of 2014-11-09 via svn using the command line listed in the "Source" web page)
[ ] Other:

On what operating system?
Ubuntu 14.04 LTS, 64 bit
With what Python version? (python -V)
2.7.6

Is scapy-com installed?
Yes

Please provide any additional information below.
Tried this on two different systems, the 2nd being a "clean" install on a fresh 
machine.  Have tried using different versions of pyusb, error messages are 
slightly different but the end result is the smae (it's not working).

```

Original issue reported on code.google.com by `jmidkif...@gmail.com` on 9 Nov 2014 at 11:26

**Comment by riverloopsec** [comment]
I'm going to try and close out some old tickets from the Google Code import. Please reopen this if needed.
