### ISSUE TITLE
zborphannotify - RZRAVENUSB - NameError

### ISSUE THREAD

**Issue by b1rdi3** [riverloopsec/killerbee#83]
Trying to use the zborphannotify and there are 5 coding errors that run. Here's the command line and printout:

root@kali:~/killerbee/tools# zborphannotify -f 15 -p 0x0030 -s 0x00000000000eaa -d 1:5
Expecting 0x00000000000eaa to be the coordinator on network (PAN ID) 0x30, located on channel 15.
The device to disassociate is 0x00000000000015.
Warning: You are using pyUSB 1.x, support is in beta.
Traceback (most recent call last):
  File "/usr/local/bin/zborphannotify", line 4, in <module>
    __import__('pkg_resources').run_script('killerbee==2.6.0', 'zborphannotify')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 745, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1677, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/killerbee-2.6.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/zborphannotify", line 64, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/killerbee-2.6.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/zborphannotify", line 23, in create_orphan_mac
    
NameError: global name 'Dot15d4' is not defined

**Comment by taylorcenters** [comment]
closed - long idle
